services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend
